version: 2.1

jobs:
  build-and-test:
    docker: # run the steps with Docker
      - image: circleci/python:3.8
    steps:
      - checkout
      #Install miniconda and create the testing environment
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - run: bash miniconda.sh -b -p $HOME/miniconda
      #writing to $BASH_ENV is apparently the way to preserve an environment variable between "run" steps
      - run: echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $BASH_ENV
      - run: echo $PATH
      - run: ls $HOME/miniconda/bin
      - run: hash -r
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda update -q conda
      - run: conda info -a
      - run: conda create -q -n test-environment python=3.8 pytest nose
      #MEME installation
      - run: sudo apt-get install -y ghostscript-x
      - run: mkdir -p ~/.config/matplotlib/
      - run: "echo backend : Agg >  ~/.config/matplotlib/matplotlibrc"
      - run: cat ~/.config/matplotlib/matplotlibrc
      - run: which gs
      - run: echo 'export PERL5LIB="$HOME/perl5/lib/perl5:$PERL5LIB"' >> $BASH_ENV
      - run: curl -L http://cpanmin.us | perl - File::Which
      - run: curl -L http://cpanmin.us | perl - HTML::PullParser
      - run: curl -L http://cpanmin.us | perl - HTML::Template
      - run: curl -L http://cpanmin.us | perl - HTML::TreeBuilder
      - run: curl -L http://cpanmin.us | perl - JSON
      - run: curl -L http://cpanmin.us | perl - XML::Simple
      - run: curl -L http://cpanmin.us | perl - XML::Parser::Expat
      - run: wget http://meme-suite.org/meme-software/5.1.1/meme-5.1.1.tar.gz
      - run: tar zxf meme-5.1.1.tar.gz
      - run:
          command: | #this seems necessary for multi-line commands
            cd meme-5.1.1
            perl scripts/dependencies.pl
      - run:
          command: | #this seems necessary for multi-line commands
            cd meme-5.1.1
            ./configure --prefix=$HOME/meme --with-url=http://meme-suite.org/  --enable-serial --enable-build-libxml2 --enable-build-libxslt
      - run:
          command: | #this seems necessary for multi-line commands
            cd meme-5.1.1
            make
      #skip the MEME tests since some of them are buggy and stall the build
      # (see: https://groups.google.com/forum/#!topic/meme-suite/D3XR7Ws1gec)
      - run:
          command: | #this seems necessary for multi-line commands
            cd meme-5.1.1
            make install
      - run: echo 'export PATH="$HOME/meme/bin:$PATH"' >> $BASH_ENV
      - run: echo $PATH
      #Install modisco (and associated dependencies) - note that tensorflow is not automatically installed, so we install separately
      - run:
          command: | #this seems necessary for multi-line commands
            source activate test-environment
            pip install -e .[tensorflow]
      - run: pwd
      - run: ls
      #Actually run the tests
      - run:
          command: |
            source activate test-environment
            pytest 

workflows:
  main:
    jobs:
      - build-and-test
